# PyNEST Microcircuit: Run Simulation

This is an example script for running the microcircuit model and generating
basic plots of the network activity.


Import the necessary modules and start the time measurements.



In [3]:
import time

import nest
import network
import numpy as np
from network_params import net_dict
from sim_params import sim_dict
from stimulus_params import stim_dict

time_start = time.time()

Initialize the network with simulation, network and stimulation parameters,
then create and connect all nodes, and finally simulate.
The times for a presimulation and the main simulation are taken
independently. A presimulation is useful because the spike activity typically
exhibits a startup transient. In benchmark simulations, this transient should
be excluded from a time measurement of the state propagation phase. Besides,
statistical measures of the spike activity should only be computed after the
transient has passed.



In [4]:
net = network.Network(sim_dict, net_dict, stim_dict)
time_network = time.time()

net.create()
time_create = time.time()

net.connect()
time_connect = time.time()



Data will be written to: /home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/data/
  Directory already existed. Old data will be overwritten.

Neuron numbers are scaled by a factor of 0.001.
Indegrees are scaled by a factor of 0.001.
  Weights and DC input are adjusted to compensate.

RNG seed: 55
Total number of virtual processes: 1
Creating neuronal populations.
Creating recording devices.
  Creating spike recorders.
Creating DC generators for external stimulation.
Connecting neuronal populations recurrently.
Connecting DC generators.


In [6]:
print(net.num_neurons)
print(sum(net.num_neurons))

print(net.num_synapses)
print(sum(net.num_synapses))
print(sum(sum(net.num_synapses)))

print(net.ext_indegrees)
print(sum(net.ext_indegrees))

print(net.pops)
print(net.spike_recorders)
print(net.weight_matrix_mean)

[21  6 22  5  5  1 14  3]
77
[[45 22 20 10  3  0  2  0]
 [17  5  4  2  2  0  0  0]
 [ 4  1 24 17  1  0 15  0]
 [ 8  0 10  5  0  0  9  0]
 [11  2  6  0  2  2  1  0]
 [ 1  0  1  0  0  0  0  0]
 [ 5  1  7  1  4  0  8 11]
 [ 2  0  0  0  0  0  3  1]]
[93 31 72 35 12  2 38 12]
295
[2 2 2 2 2 2 3 2]
17
[NodeCollection(metadata=None, model=iaf_psc_exp, size=21, first=1, last=21), NodeCollection(metadata=None, model=iaf_psc_exp, size=6, first=22, last=27), NodeCollection(metadata=None, model=iaf_psc_exp, size=22, first=28, last=49), NodeCollection(metadata=None, model=iaf_psc_exp, size=5, first=50, last=54), NodeCollection(metadata=None, model=iaf_psc_exp, size=5, first=55, last=59), NodeCollection(metadata=None, model=iaf_psc_exp, size=1, first=60), NodeCollection(metadata=None, model=iaf_psc_exp, size=14, first=61, last=74), NodeCollection(metadata=None, model=iaf_psc_exp, size=3, first=75, last=77)]
NodeCollection(metadata=None, model=spike_recorder, size=8, first=78, last=85)
[[  2776.74837

In [43]:
def extract_syn_info_neuroring(net):
    """Extract synapse information from the network"""
    
    print("Extracting synapse information...")
    # create a list to store the synapse data
    synapse_data = []
    
    # First, extract connections between neuron populations (as before)
    for i, target_pop in enumerate(net.pops):
        for j, source_pop in enumerate(net.pops):
            if net.num_synapses[i][j] > 0:
                connections = nest.GetConnections(source=source_pop, target=target_pop)
                if len(connections) > 0:
                    conn_info = nest.GetStatus(connections, ['source', 'target', 'weight', 'delay'])
                    sources, targets, weights, delays = zip(*conn_info)
                    sources = np.array(sources)
                    targets = np.array(targets)
                    weights = np.array(weights)
                    delays = np.array(delays)
                    
                    # make the row source, target, delay, weight
                    # directly append to the synapse_data
                    synapse_data.append([sources, targets, delays, weights])
    
    # sort the row by source, so make similar source together
    synapse_data.sort(key=lambda x: x[0])
                    
    return synapse_data
                
                
def extract_synapse_info(net):
    """Extract detailed synapse information from the network including all node types"""
    
    print("Extracting synapse information...")
    synapse_data = {}
    
    # First, extract connections between neuron populations (as before)
    for i, target_pop in enumerate(net.pops):
        for j, source_pop in enumerate(net.pops):
            if net.num_synapses[i][j] > 0:
                print(f"Extracting connections from population {j} to population {i}")
                print(f"  Expected synapses: {net.num_synapses[i][j]}")
                
                connections = nest.GetConnections(source=source_pop, target=target_pop)
                
                if len(connections) > 0:
                    # GetStatus returns list of tuples: (source, target, weight, delay)
                    conn_info = nest.GetStatus(connections, ['source', 'target', 'weight', 'delay'])
                    sources, targets, weights, delays = zip(*conn_info)

                    # Convert to NumPy arrays
                    sources = np.array(sources)
                    targets = np.array(targets)
                    weights = np.array(weights)
                    delays = np.array(delays)

                    key = f"pop{j}_to_pop{i}"
                    synapse_data[key] = {
                        'source_pop': j,
                        'target_pop': i,
                        'source_type': 'neuron_population',
                        'target_type': 'neuron_population',
                        'source_neurons': sources,
                        'target_neurons': targets,
                        'weights': weights,
                        'delays': delays,
                        'num_synapses': len(sources)
                    }

                    print(f"  Actual synapses extracted: {len(sources)}")
                    print(f"  Weight range: {np.min(weights):.3f} to {np.max(weights):.3f} pA")
                    print(f"  Delay range: {np.min(delays):.3f} to {np.max(delays):.3f} ms\n")
                else:
                    print(f"  No connections found!\n")
        
    # Extract connections from neuron populations to spike_recorder
    print("Extracting connections from neuron populations to spike_recorder...")
    for i, source_pop in enumerate(net.pops):
        connections = nest.GetConnections(source=source_pop, target=net.spike_recorders)
        
        if len(connections) > 0:
            print(f"  Population {i} to spike_recorder")
            
            conn_info = nest.GetStatus(connections, ['source', 'target', 'weight', 'delay'])
            sources, targets, weights, delays = zip(*conn_info)

            sources = np.array(sources)
            targets = np.array(targets)
            weights = np.array(weights)
            delays = np.array(delays)

            key = f"pop{i}_to_spike_recorder"
            synapse_data[key] = {
                'source_pop': i,
                'target_pop': -2,  # -2 indicates spike_recorder
                'source_type': 'neuron_population',
                'target_type': 'spike_recorder',
                'source_neurons': sources,
                'target_neurons': targets,
                'weights': weights,
                'delays': delays,
                'num_synapses': len(sources)
            }

            print(f"    Synapses extracted: {len(sources)}")
            print(f"    Weight range: {np.min(weights):.3f} to {np.max(weights):.3f} pA")
            print(f"    Delay range: {np.min(delays):.3f} to {np.max(delays):.3f} ms\n")
    
    # Extract any other connections that might exist
    print("Extracting any other connections in the network...")
    
    # Get all connections in the network
    all_connections = nest.GetConnections()
    
    # Get all node IDs in the network
    all_nodes = []
    for pop in net.pops:
        all_nodes.extend(pop.tolist())
    all_nodes.extend(net.spike_recorders.tolist())
    all_nodes = set(all_nodes)
    
    # Find connections that haven't been captured yet
    captured_connections = set()
    for data in synapse_data.values():
        for i in range(len(data['source_neurons'])):
            captured_connections.add((data['source_neurons'][i], data['target_neurons'][i]))
        
    return synapse_data

def save_synapse_data(synapse_data, filename="synapse_data.txt"):
    """Save synapse data to a text file"""
    
    with open(filename, 'w') as f:
        f.write("Detailed Synapse Information\n")
        f.write("=" * 50 + "\n\n")
        
        for key, data in synapse_data.items():
            f.write(f"Connection: Population {data['source_pop']} → Population {data['target_pop']}\n")
            f.write(f"Number of synapses: {data['num_synapses']}\n")
            f.write(f"Weight range: {np.min(data['weights']):.3f} to {np.max(data['weights']):.3f} pA\n")
            f.write(f"Delay range: {np.min(data['delays']):.3f} to {np.max(data['delays']):.3f} ms\n")
            f.write("-" * 30 + "\n")
            
            # Write first 10 synapses as example
            f.write("First 10 synapses (source → target: weight, delay):\n")
            for k in range(min(10, len(data['source_neurons']))):
                f.write(f"  {data['source_neurons'][k]} → {data['target_neurons'][k]}: "
                       f"{data['weights'][k]:.3f} pA, {data['delays'][k]:.3f} ms\n")
            
            f.write("\n" + "=" * 50 + "\n\n")
    
    print(f"Synapse data saved to {filename}")

def save_synapse_csv(synapse_data, filename="synapses.csv"):
    """Save all synapses to a CSV file"""
    
    with open(filename, 'w') as f:
        f.write("source_neuron,target_neuron,weight,delay,source_pop,target_pop\n")
        
        for key, data in synapse_data.items():
            for i in range(len(data['source_neurons'])):
                f.write(f"{data['source_neurons'][i]},{data['target_neurons'][i]},"
                       f"{data['weights'][i]:.6f},{data['delays'][i]:.6f},"
                       f"{data['source_pop']},{data['target_pop']}\n")
    
    print(f"All synapses saved to {filename}")

def main():
    # Create and connect the network
    #print("Creating network...")
    #net = network.Network(sim_dict, net_dict, stim_dict)
    #net.create()
    #net.connect()
    
    # Extract synapse information
    synapse_data = extract_synapse_info(net)
    
    # Save data
    save_synapse_data(synapse_data)
    save_synapse_csv(synapse_data)
    
    # Print summary
    total_synapses = sum(data['num_synapses'] for data in synapse_data.values())
    print(f"\nTotal synapses extracted: {total_synapses}")
    
    # Show some statistics
    all_weights = np.concatenate([data['weights'] for data in synapse_data.values()])
    all_delays = np.concatenate([data['delays'] for data in synapse_data.values()])
    
    print(f"\nOverall statistics:")
    print(f"Weight mean: {np.mean(all_weights):.3f} pA, std: {np.std(all_weights):.3f} pA")
    print(f"Delay mean: {np.mean(all_delays):.3f} ms, std: {np.std(all_delays):.3f} ms")

if __name__ == "__main__":
    main() 

Extracting synapse information...
Extracting connections from population 0 to population 0
  Expected synapses: 45
  Actual synapses extracted: 45
  Weight range: 2098.304 to 3539.695 pA
  Delay range: 0.400 to 3.300 ms

Extracting connections from population 1 to population 0
  Expected synapses: 22
  Actual synapses extracted: 22
  Weight range: -12752.110 to -8681.262 pA
  Delay range: 0.100 to 1.400 ms

Extracting connections from population 2 to population 0
  Expected synapses: 20
  Actual synapses extracted: 20
  Weight range: 4153.749 to 6886.188 pA
  Delay range: 0.200 to 2.700 ms

Extracting connections from population 3 to population 0
  Expected synapses: 10
  Actual synapses extracted: 10
  Weight range: -12102.117 to -8945.970 pA
  Delay range: 0.300 to 0.900 ms

Extracting connections from population 4 to population 0
  Expected synapses: 3
  Actual synapses extracted: 3
  Weight range: 2517.834 to 2805.667 pA
  Delay range: 2.400 to 2.600 ms

Extracting connections from

In [56]:
import struct
from collections import defaultdict

def extract_syn_info_neuroring(net):
    """Extract all synapse connections as a flat array: [source, target, delay, weight] per row."""
    print("Extracting synapse information...")
    synapse_list = []

    for i, target_pop in enumerate(net.pops):
        for j, source_pop in enumerate(net.pops):
            if net.num_synapses[i][j] > 0:
                connections = nest.GetConnections(source=source_pop, target=target_pop)
                if len(connections) > 0:
                    conn_info = nest.GetStatus(connections, ['source', 'target', 'weight', 'delay'])
                    for source, target, weight, delay in conn_info:
                        synapse_list.append([source, target, int(delay*10), weight])
    synapse_list.sort(key=lambda x: x[0])
    
    # create a new list to store array for neuroring kernel
    # --- Create packed_list ---
    if not synapse_list:
        return synapse_list, []

    # Find max source neuron
    max_source = max(row[0] for row in synapse_list)
    block_size = 5000
    packed_list = [0] * ((max_source + 1) * block_size)

    # Group synapses by source
    source_dict = defaultdict(list)
    for row in synapse_list:
        source_dict[row[0]].append(row)

    for source, syns in source_dict.items():
        base_idx = source * block_size
        packed_list[base_idx] = len(syns)
        print(f"Filling block for source {source} at index {base_idx}, count {len(syns)}")
        for i, (src, tgt, dly, wgt) in enumerate(syns):
            # target: 24 bits, delay: 8 bits, weight: 32 bits float
            tgt = int(tgt) & 0xFFFFFF
            dly = int(dly) & 0xFF
            # pack weight as float32 bits
            wgt_bits = struct.unpack('>I', struct.pack('>f', float(wgt)))[0]  # big-endian
            packed = (wgt_bits << 32) | (dly << 24) | tgt
            packed_list[base_idx + 1 + i] = packed

    return synapse_list, packed_list

synapse_list, packed_list = extract_syn_info_neuroring(net)
print(synapse_list)
print(packed_list[1*5000 : 1*5000+10])
print(packed_list[2*5000 : 2*5000+10])
print(packed_list[3*5000 : 3*5000+10])
print(packed_list[4*5000 : 4*5000+10])
print(packed_list[5*5000 : 5*5000+10])
print(packed_list[6*5000 : 6*5000+10])
print(packed_list[7*5000 : 7*5000+10])
print(packed_list[8*5000 : 8*5000+10])
print(packed_list[9*5000 : 9*5000+10])
print(packed_list[10*5000 : 10*5000+10])

Extracting synapse information...
Filling block for source 1 at index 5000, count 6
Filling block for source 2 at index 10000, count 2
Filling block for source 3 at index 15000, count 3
Filling block for source 5 at index 25000, count 3
Filling block for source 6 at index 30000, count 6
Filling block for source 7 at index 35000, count 5
Filling block for source 8 at index 40000, count 3
Filling block for source 9 at index 45000, count 3
Filling block for source 10 at index 50000, count 2
Filling block for source 11 at index 55000, count 4
Filling block for source 12 at index 60000, count 6
Filling block for source 13 at index 65000, count 8
Filling block for source 14 at index 70000, count 4
Filling block for source 15 at index 75000, count 6
Filling block for source 16 at index 80000, count 6
Filling block for source 17 at index 85000, count 4
Filling block for source 18 at index 90000, count 11
Filling block for source 19 at index 95000, count 3
Filling block for source 20 at index 1

In [54]:
print(packed_list[1*5000 : 1*5000+10])

[6, 4983073026191917076, 4983555741743841288, 4987400373296693253, 4986240663289856003, 4980988399356739643, 4982619619446489151, 0, 0, 0]


In [37]:
all_connections = nest.GetConnections()

print(nest.GetConnections())


# get network info
print(net.num_neurons)
print(sum(net.num_neurons))
print(net.num_synapses)
print(sum(net.num_synapses))
print(net.ext_indegrees)
print(sum(net.ext_indegrees))
print(net.pops)
print(net.spike_recorders)
print(net.dc_stim_input)

connect_info = nest.GetConnections(source=net.dc_stim_input, target=net.pops[0])
print(net.dc_stim_input.origin)
print(net.dc_stim_input.stop)
print(net.dc_stim_input.stimulus_source)
print(net.dc_stim_input.start)
print(net.dc_stim_input.amplitude)


# get list of neuron in population 4


 source   target   synapse model   weight   delay 
-------- -------- --------------- -------- -------
      1       20  static_synapse    2679.   1.600
      1       63  static_synapse    2653.   2.000
      1        8  static_synapse    2706.  0.9000
      1        5  static_synapse    2925.   1.900
      1       59  static_synapse    2560.   1.400
      1        3  static_synapse    2859.   1.200
      2       23  static_synapse    3039.   1.400
      2        6  static_synapse    2810.  0.5000
      3       62  static_synapse    2256.   2.000
      3       15  static_synapse    2953.   1.500
      3       56  static_synapse    2830.   2.500
      5        1  static_synapse    2599.   2.100
      5       55  static_synapse    2898.  0.7000
      5       10  static_synapse    2399.   1.000
      6       51  static_synapse    3037.   1.800
     ⋮        ⋮               ⋮        ⋮       ⋮ 
     92       63  static_synapse    1.000   1.000
     92       64  static_synapse    1.000   1.00

In [41]:
# get list of neuron in population 1
print(net.pops[0].get("V_th"))


(-50.0, -50.0, -50.0, -50.0, -50.0, -50.0, -50.0, -50.0, -50.0, -50.0, -50.0, -50.0, -50.0, -50.0, -50.0, -50.0, -50.0, -50.0, -50.0, -50.0, -50.0)


In [17]:
net.simulate(sim_dict["t_presim"])
time_presimulate = time.time()

net.simulate(sim_dict["t_sim"])
time_simulate = time.time()

Simulating 500.0 ms.
Simulating 1000.0 ms.


Plot a spike raster of the simulated neurons and a box plot of the firing
rates for each population.
For visual purposes only, spikes 100 ms before and 100 ms after the thalamic
stimulus time are plotted here by default.
The computation of spike rates discards the presimulation time to exclude
initialization artifacts.



In [18]:
raster_plot_interval = np.array([stim_dict["th_start"] - 100.0, stim_dict["th_start"] + 100.0])
firing_rates_interval = np.array([sim_dict["t_presim"], sim_dict["t_presim"] + sim_dict["t_sim"]])
net.evaluate(raster_plot_interval, firing_rates_interval)
time_evaluate = time.time()

Interval to plot spikes: [600. 800.] ms


/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/helpers.py:426: UserWarning:loadtxt: input contained no data: "/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/data/spike_recorder-78-0.dat"
/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/helpers.py:426: UserWarning:loadtxt: input contained no data: "/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/data/spike_recorder-79-0.dat"
/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/helpers.py:426: UserWarning:loadtxt: input contained no data: "/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/data/spike_recorder-80-0.dat"
/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/helpers.py:426: UserWarning:loadtxt: input contained no data: "/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/data/spike_recorder-81-0.dat"
/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/helpers.py:426: UserWarning:loadtxt: input contained no data: "/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/data/spike_recorder-82-0.

Interval to compute firing rates: [ 500. 1500.] ms
Mean rates: [0. 0. 0. 0. 0. 0. 0. 0.] spikes/s
Standard deviation of rates: [0. 0. 0. 0. 0. 0. 0. 0.] spikes/s


/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/helpers.py:426: UserWarning:loadtxt: input contained no data: "/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/data/spike_recorder-78-0.dat"
/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/helpers.py:426: UserWarning:loadtxt: input contained no data: "/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/data/spike_recorder-79-0.dat"
/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/helpers.py:426: UserWarning:loadtxt: input contained no data: "/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/data/spike_recorder-80-0.dat"
/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/helpers.py:426: UserWarning:loadtxt: input contained no data: "/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/data/spike_recorder-81-0.dat"
/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/helpers.py:426: UserWarning:loadtxt: input contained no data: "/home/miahafiz/NeuroRing/host_py/corticalmicrocircuit/data/spike_recorder-82-0.

Summarize time measurements. Rank 0 usually takes longest because of the
data evaluation and print calls.



In [16]:
print(
    "\nTimes of Rank {}:\n".format(nest.Rank())
    + "  Total time:          {:.3f} s\n".format(time_evaluate - time_start)
    + "  Time to initialize:  {:.3f} s\n".format(time_network - time_start)
    + "  Time to create:      {:.3f} s\n".format(time_create - time_network)
    + "  Time to connect:     {:.3f} s\n".format(time_connect - time_create)
    + "  Time to presimulate: {:.3f} s\n".format(time_presimulate - time_connect)
    + "  Time to simulate:    {:.3f} s\n".format(time_simulate - time_presimulate)
    + "  Time to evaluate:    {:.3f} s\n".format(time_evaluate - time_simulate)
)

NameError: name 'time_presimulate' is not defined